module:
  imports:
  - path: github.com/theNewDynamic/hugo-module-imgix
    mounts:
      - source: func
        target: layouts/partials/func
      - source: markup
        target: layouts/_markup
      - source: data
        target: data